files: ^backend/
repos:
  - repo: git@github.com:PyCQA/autoflake.git
    rev: v1.4
    hooks:
    -     id: autoflake
          args: [ '--in-place', '--remove-all-unused-imports' ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
        args: [ "backend/app/.env", "README.md" ]
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
        - id: black
          args: [ --line-length, '120' ]
          language_version: python3.10
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        exclude: ^base.py$
        args:
          - "--max-line-length=120"
